name: Daily GitHub Pages Deploy

on:
  schedule:
    - cron: "5 0 * * *" # todo dia às 00:05 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create empty commit to trigger Pages
        run: |
          git commit --allow-empty -m "Daily GitHub Pages deploy"

      - name: Push changes
        run: |
          git push origin main
