name: Daily Email

on:
  schedule:
    - cron: '0 6 * * *'

  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send HTML email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true

          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}

          subject: Relatório Diário HTML

          to: ${{ secrets.EMAIL_USERNAME }}

          from: GitHub Actions

          html_body: file://templates/daily-report.html
